# CodeRabbit Configuration
# Copy this file to your project root to enable automated PR reviews.
# Full documentation: https://docs.coderabbit.ai/getting-started/configuration
#
# Free tier note:
#   Open source repos → full line-by-line reviews on all tiers
#   Private repos → PR summaries only after 14-day Pro trial
#   Automated review-fix loop requires Lite plan or higher (full reviews needed)

language: "en-US"

reviews:
  # "chill" = fewer comments, "assertive" = thorough reviews
  profile: "assertive"

  # Automatically review new PRs
  auto_review:
    enabled: true
    drafts: false

  # Path-specific review instructions (customize for your project)
  path_instructions:
    - path: "**/*.test.*"
      instructions: "Focus on test coverage completeness and edge cases."
    - path: "**/*.md"
      instructions: "Check for broken links, formatting consistency, and accuracy."
    # - path: "src/**"
    #   instructions: "Enforce project conventions and type safety."
    # - path: "generated/**"
    #   instructions: "Skip review — these files are auto-generated."

chat:
  auto_reply: true
