name: Claude Code Fix/Create

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-fix:
    # Only run when comment starts with @claude-fix or @claude-create
    if: |
      (github.event_name == 'issue_comment' || github.event_name == 'pull_request_review_comment') &&
      (startsWith(github.event.comment.body, '@claude-fix') || startsWith(github.event.comment.body, '@claude-create'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Check permissions
        id: check_permissions
        run: |
          # Add your GitHub username(s) here
          AUTHORIZED_USERS="your-github-username"
          COMMENTER="${{ github.event.comment.user.login }}"

          if echo "$AUTHORIZED_USERS" | grep -qw "$COMMENTER"; then
            echo "authorized=true" >> $GITHUB_OUTPUT
          else
            echo "authorized=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        if: steps.check_permissions.outputs.authorized == 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load instructions
        if: steps.check_permissions.outputs.authorized == 'true'
        id: load_instructions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get issue metadata
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY=$(gh issue view "$ISSUE_NUMBER" --json body -q '.body')
          REPOSITORY="${{ github.repository }}"
          TRIGGERED_BY="${{ github.event.comment.user.login }}"
          BRANCH_NAME="claude/issue-${ISSUE_NUMBER}"

          # Load prompt template based on issue labels
          LABELS=$(gh issue view "$ISSUE_NUMBER" --json labels -q '.labels[].name')
          if echo "$LABELS" | grep -qiE "enhancement|feature|new feature"; then
            TEMPLATE=$(cat .github/workflows/prompts/end-to-end-feature-github.md)
          else
            TEMPLATE=$(cat .github/workflows/prompts/bug-fix-github.md)
          fi

          # Substitute variables
          TEMPLATE="${TEMPLATE//\$REPOSITORY/$REPOSITORY}"
          TEMPLATE="${TEMPLATE//\$ISSUE_NUMBER/$ISSUE_NUMBER}"
          TEMPLATE="${TEMPLATE//\$ISSUE_TITLE/$ISSUE_TITLE}"
          TEMPLATE="${TEMPLATE//\$TRIGGERED_BY/$TRIGGERED_BY}"
          TEMPLATE="${TEMPLATE//\$BRANCH_NAME/$BRANCH_NAME}"
          TEMPLATE="${TEMPLATE//\$CREATE_BRANCH/true}"
          TEMPLATE="${TEMPLATE//\$CREATE_PR/false}"
          TEMPLATE="${TEMPLATE//\$COMMENT_ON_ISSUE/true}"
          TEMPLATE="${TEMPLATE//\$ISSUE_BODY/$ISSUE_BODY}"

          # Save processed template
          echo "$TEMPLATE" > /tmp/claude_instructions.md
          echo "instructions_file=/tmp/claude_instructions.md" >> $GITHUB_OUTPUT

      - name: Run Claude Code
        if: steps.check_permissions.outputs.authorized == 'true'
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          model: "claude-sonnet-4-5-20250929"
          direct_prompt: "true"
          custom_instructions: |
            $(cat /tmp/claude_instructions.md)

      - name: Unauthorized user
        if: steps.check_permissions.outputs.authorized == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Unauthorized: You do not have permission to trigger Claude Code.'
            })
