name: Claude Code Review (Read Only)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-review:
    if: |
      (
        github.event_name == 'issue_comment' ||
        github.event_name == 'pull_request_review_comment'
      ) &&
      contains(github.event.comment.body, '@claude-review') &&
      contains(fromJSON('["ryanjosebrosas"]'), github.event.comment.user.login)

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR number
        run: |
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            echo "PR_NUM=${{ github.event.issue.number }}" >> $GITHUB_ENV
          else
            echo "PR_NUM=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          fi

      - name: Load instructions
        id: load-instructions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TEMPLATE=$(cat .github/workflows/prompts/code-review-github.md)
          TEMPLATE="${TEMPLATE//\$REPOSITORY/${{ github.repository }}}"
          TEMPLATE="${TEMPLATE//\$PR_NUMBER/$PR_NUM}"
          TEMPLATE="${TEMPLATE//\$TRIGGERED_BY/${{ github.event.comment.user.login }}}"
          TEMPLATE="${TEMPLATE//\$IF_COMMENT_ON_PR/}"
          TEMPLATE="${TEMPLATE//\$ENDIF_COMMENT_ON_PR/}"

          # Use unique delimiter to avoid escaping issues
          DELIMITER="INSTRUCTIONS_$(date +%s)_EOF"
          echo "CUSTOM_INSTRUCTIONS<<${DELIMITER}" >> $GITHUB_OUTPUT
          echo "$TEMPLATE" >> $GITHUB_OUTPUT
          echo "${DELIMITER}" >> $GITHUB_OUTPUT

      - name: Run Claude Code Review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          custom_instructions: ${{ steps.load-instructions.outputs.CUSTOM_INSTRUCTIONS }}
          direct_prompt: "true"

  unauthorized:
    if: |
      (
        github.event_name == 'issue_comment' ||
        github.event_name == 'pull_request_review_comment'
      ) &&
      contains(github.event.comment.body, '@claude-review') &&
      !contains(fromJSON('["ryanjosebrosas"]'), github.event.comment.user.login)

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const comment = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ @${context.actor} - Not authorized`
            };

            if (context.eventName === 'issue_comment') {
              await github.rest.issues.createComment({
                ...comment,
                issue_number: context.issue.number
              });
            } else if (context.eventName === 'pull_request_review_comment') {
              await github.rest.pulls.createReplyForReviewComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                comment_id: context.payload.comment.id,
                body: comment.body
              });
            }
