name: Codex Fix (Write Access)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  codex-fix:
    if: |
      (
        github.event_name == 'issue_comment' ||
        github.event_name == 'pull_request_review_comment'
      ) &&
      (contains(github.event.comment.body, '@codex-fix') || contains(github.event.comment.body, '@codex-create')) &&
      contains(fromJSON('["ryanjosebrosas"]'), github.event.comment.user.login)

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Git
        run: |
          git config user.name "codex-bot"
          git config user.email "codex-bot@users.noreply.github.com"

      - name: Get Issue Number
        run: |
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            echo "ISSUE_NUM=${{ github.event.issue.number }}" >> $GITHUB_ENV
          else
            echo "ISSUE_NUM=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          fi

      - name: Load instructions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_JSON=$(gh issue view $ISSUE_NUM --json labels,title,body)
          LABELS=$(echo "$ISSUE_JSON" | jq -r '.labels[].name' | tr '\n' ' ')
          TITLE=$(echo "$ISSUE_JSON" | jq -r '.title')
          BODY=$(echo "$ISSUE_JSON" | jq -r '.body')

          if echo "$LABELS" | grep -qiE "enhancement|feature|new feature"; then
            TEMPLATE_FILE=".github/workflows/prompts/end-to-end-feature-github.md"
          elif echo "$LABELS" | grep -qi "bug"; then
            TEMPLATE_FILE=".github/workflows/prompts/bug-fix-github.md"
          else
            TEMPLATE_FILE=".github/workflows/prompts/bug-fix-github.md"
          fi

          TEMPLATE=$(cat $TEMPLATE_FILE)
          TEMPLATE="${TEMPLATE//\$REPOSITORY/${{ github.repository }}}"
          TEMPLATE="${TEMPLATE//\$ISSUE_NUMBER/$ISSUE_NUM}"
          TEMPLATE="${TEMPLATE//\$ISSUE_TITLE/$TITLE}"
          TEMPLATE="${TEMPLATE//\$ISSUE_BODY/$BODY}"
          TEMPLATE="${TEMPLATE//\$TRIGGERED_BY/${{ github.event.comment.user.login }}}"
          TEMPLATE="${TEMPLATE//\$BRANCH_NAME/fix/issue-$ISSUE_NUM-codex}"
          TEMPLATE="${TEMPLATE//\$CREATE_BRANCH/false}"
          TEMPLATE="${TEMPLATE//\$CREATE_PR/false}"
          TEMPLATE="${TEMPLATE//\$COMMENT_ON_ISSUE/false}"
          TEMPLATE="${TEMPLATE//\$PLAN_PATH/}"

          echo "$TEMPLATE" > /tmp/codex_prompt.txt

      - name: Run Codex
        id: codex
        uses: openai/codex-action@v1
        timeout-minutes: 30
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt-file: /tmp/codex_prompt.txt
          sandbox: workspace-write

      - name: Get issue title for PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TITLE=$(gh issue view $ISSUE_NUM --json title --jq '.title')
          echo "ISSUE_TITLE=$TITLE" >> $GITHUB_ENV

      - name: Create PR with changes
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "fix: ${{ env.ISSUE_TITLE }} (#${{ env.ISSUE_NUM }})"
          branch: fix/issue-${{ env.ISSUE_NUM }}-codex
          title: "Fix: ${{ env.ISSUE_TITLE }}"
          body: |
            ## Summary

            Fixes #${{ env.ISSUE_NUM }}

            ## Changes Made

            This PR was automatically generated by Codex to address the issue.

            ## Testing

            - Documentation-only change
            - No code execution required

            ---

            🤖 *Automated fix by Codex*

      - name: Comment on issue
        if: steps.create-pr.outputs.pull-request-number
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = '${{ steps.create-pr.outputs.pull-request-number }}';
            const prUrl = '${{ steps.create-pr.outputs.pull-request-url }}';

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ env.ISSUE_NUM }},
              body: `## 🤖 Codex Fix Complete\n\n✅ I've analyzed the issue and implemented a fix.\n\n**Pull Request**: #${prNumber}\n**Branch**: \`fix/issue-${{ env.ISSUE_NUM }}-codex\`\n\nThe fix has been committed and is ready for review. All changes follow the project conventions documented in CLAUDE.md.`
            });

  unauthorized:
    if: |
      (
        github.event_name == 'issue_comment' ||
        github.event_name == 'pull_request_review_comment'
      ) &&
      (contains(github.event.comment.body, '@codex-fix') || contains(github.event.comment.body, '@codex-create')) &&
      !contains(fromJSON('["ryanjosebrosas"]'), github.event.comment.user.login)

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            if (context.eventName === 'issue_comment') {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `❌ @${context.actor} - Not authorized`
              });
            }
