name: Cursor Review (Read Only)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  cursor-review:
    if: |
      (
        github.event_name == 'issue_comment' ||
        github.event_name == 'pull_request_review_comment'
      ) &&
      contains(github.event.comment.body, '@cursor-review') &&
      contains(fromJSON('["ryanjosebrosas"]'), github.event.comment.user.login)

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Cursor CLI
        run: |
          curl https://cursor.com/install -fsS | bash
          echo "$HOME/.cursor/bin" >> $GITHUB_PATH

      - name: Get PR number
        run: |
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            echo "PR_NUM=${{ github.event.issue.number }}" >> $GITHUB_ENV
          else
            echo "PR_NUM=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          fi

      - name: Load instructions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TEMPLATE=$(cat .github/workflows/prompts/code-review-github.md)
          TEMPLATE="${TEMPLATE//\$REPOSITORY/${{ github.repository }}}"
          TEMPLATE="${TEMPLATE//\$PR_NUMBER/$PR_NUM}"
          TEMPLATE="${TEMPLATE//\$TRIGGERED_BY/${{ github.event.comment.user.login }}}"
          TEMPLATE="${TEMPLATE//\$IF_COMMENT_ON_PR/}"
          TEMPLATE="${TEMPLATE//\$ENDIF_COMMENT_ON_PR/}"

          echo "$TEMPLATE" > /tmp/cursor_review_prompt.txt

      - name: Run Cursor Review
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cursor-agent -p "$(cat /tmp/cursor_review_prompt.txt)" --model gpt-5 --force

  unauthorized:
    if: |
      (
        github.event_name == 'issue_comment' ||
        github.event_name == 'pull_request_review_comment'
      ) &&
      contains(github.event.comment.body, '@cursor-review') &&
      !contains(fromJSON('["ryanjosebrosas"]'), github.event.comment.user.login)

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const comment = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ @${context.actor} - Not authorized`
            };

            if (context.eventName === 'issue_comment') {
              await github.rest.issues.createComment({
                ...comment,
                issue_number: context.issue.number
              });
            } else if (context.eventName === 'pull_request_review_comment') {
              await github.rest.pulls.createReplyForReviewComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                comment_id: context.payload.comment.id,
                body: comment.body
              });
            }
