name: Cursor Fix (Write Access)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  cursor-fix:
    if: |
      (
        github.event_name == 'issue_comment' ||
        github.event_name == 'pull_request_review_comment'
      ) &&
      (contains(github.event.comment.body, '@cursor-fix') || contains(github.event.comment.body, '@cursor-create')) &&
      contains(fromJSON('["ryanjosebrosas"]'), github.event.comment.user.login)

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Cursor CLI
        run: |
          curl https://cursor.com/install -fsS | bash
          echo "$HOME/.cursor/bin" >> $GITHUB_PATH

      - name: Load instructions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            NUM="${{ github.event.issue.number }}"
          else
            NUM="${{ github.event.pull_request.number }}"
          fi

          ISSUE_JSON=$(gh issue view $NUM --json labels,title,body)
          LABELS=$(echo "$ISSUE_JSON" | jq -r '.labels[].name' | tr '\n' ' ')
          TITLE=$(echo "$ISSUE_JSON" | jq -r '.title')
          BODY=$(echo "$ISSUE_JSON" | jq -r '.body')

          if echo "$LABELS" | grep -qiE "enhancement|feature|new feature"; then
            TEMPLATE_FILE=".github/workflows/prompts/end-to-end-feature-github.md"
          elif echo "$LABELS" | grep -qi "bug"; then
            TEMPLATE_FILE=".github/workflows/prompts/bug-fix-github.md"
          else
            TEMPLATE_FILE=".github/workflows/prompts/bug-fix-github.md"
          fi

          TEMPLATE=$(cat $TEMPLATE_FILE)
          TEMPLATE="${TEMPLATE//\$REPOSITORY/${{ github.repository }}}"
          TEMPLATE="${TEMPLATE//\$ISSUE_NUMBER/$NUM}"
          TEMPLATE="${TEMPLATE//\$ISSUE_TITLE/$TITLE}"
          TEMPLATE="${TEMPLATE//\$ISSUE_BODY/$BODY}"
          TEMPLATE="${TEMPLATE//\$TRIGGERED_BY/${{ github.event.comment.user.login }}}"
          TEMPLATE="${TEMPLATE//\$BRANCH_NAME/fix/issue-$NUM-cursor}"
          TEMPLATE="${TEMPLATE//\$CREATE_BRANCH/true}"
          TEMPLATE="${TEMPLATE//\$CREATE_PR/true}"
          TEMPLATE="${TEMPLATE//\$COMMENT_ON_ISSUE/true}"
          TEMPLATE="${TEMPLATE//\$PLAN_PATH/}"

          echo "$TEMPLATE" > /tmp/cursor_prompt.txt

      - name: Run Cursor
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cursor-agent -p "$(cat /tmp/cursor_prompt.txt)" --model gpt-5 --force

  unauthorized:
    if: |
      (
        github.event_name == 'issue_comment' ||
        github.event_name == 'pull_request_review_comment'
      ) &&
      (contains(github.event.comment.body, '@cursor-fix') || contains(github.event.comment.body, '@cursor-create')) &&
      !contains(fromJSON('["ryanjosebrosas"]'), github.event.comment.user.login)

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            if (context.eventName === 'issue_comment') {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `❌ @${context.actor} - Not authorized`
              });
            }
