name: Disable Auto-Merge on New Commits

# Disable auto-merge when new commits are pushed after CodeRabbit approval
# This ensures CodeRabbit re-reviews the new commits before PR can merge
on:
  pull_request:
    types: [synchronize]  # Triggered when commits are pushed to PR

concurrency:
  group: disable-automerge-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  disable-auto-merge:
    # Only run if auto-merge is currently enabled
    if: github.event.pull_request.auto_merge != null

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Disable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"

          echo "New commits pushed to PR #$PR_NUMBER"
          echo "Auto-merge is currently enabled - disabling to allow CodeRabbit re-review..."

          # Disable auto-merge
          gh pr merge --disable-auto "$PR_NUMBER" --repo ${{ github.repository }}

          echo "✓ Auto-merge disabled. CodeRabbit will re-review the new commits."

      - name: Post explanation comment
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ github.event.pull_request.number }};

            const message = '🔄 **New commits detected** - auto-merge disabled.\n\n' +
                          'CodeRabbit will re-review the changes. Auto-merge will be re-enabled if CodeRabbit approves.\n\n' +
                          '_This ensures all code is reviewed before merging._';

            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
