name: Cursor Review (Read-Only)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  cursor-review:
    # Only trigger on @cursor-review command from authorized users
    if: |
      (
        github.event_name == 'issue_comment' ||
        github.event_name == 'pull_request_review_comment'
      ) &&
      contains(github.event.comment.body, '@cursor-review') &&
      contains(fromJSON('["ryanjosebrosas"]'), github.event.comment.user.login)

    runs-on: ubuntu-latest

    permissions:
      contents: read # Read-only access
      pull-requests: write # Allow comments on PRs
      issues: write # Allow comments on issues
      actions: read # Read CI results
      id-token: write # Required for OIDC authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better context

      - name: Configure Git
        run: |
          git config user.name "cursor-bot"
          git config user.email "cursor-bot@users.noreply.github.com"

      - name: Install Cursor CLI
        run: |
          curl https://cursor.com/install -fsS | bash
          echo "$HOME/.cursor/bin" >> $GITHUB_PATH

      - name: Load review instructions
        id: load-instructions
        run: |
          # Get the PR number from the event
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            PR_NUMBER="${{ github.event.issue.number }}"
          else
            PR_NUMBER="${{ github.event.pull_request.number }}"
          fi

          # Read the code review command template
          INSTRUCTIONS=$(cat .claude/commands/validation/code-review.md)

          # Prepend context
          echo "# GitHub Context" > /tmp/cursor_review_prompt.txt
          echo "- Repository: ${{ github.repository }}" >> /tmp/cursor_review_prompt.txt
          echo "- PR Number: ${PR_NUMBER}" >> /tmp/cursor_review_prompt.txt
          echo "- Triggered by: ${{ github.event.comment.user.login }}" >> /tmp/cursor_review_prompt.txt
          echo "" >> /tmp/cursor_review_prompt.txt
          echo "# Pull Request Code Review" >> /tmp/cursor_review_prompt.txt
          echo "" >> /tmp/cursor_review_prompt.txt
          echo "You are reviewing a pull request in a GitHub Actions runner." >> /tmp/cursor_review_prompt.txt
          echo "After completing the review, save your findings to:" >> /tmp/cursor_review_prompt.txt
          echo "\`.agents/code-reviews/pr-${PR_NUMBER}-review.md\`" >> /tmp/cursor_review_prompt.txt
          echo "" >> /tmp/cursor_review_prompt.txt
          echo "Then post a comment on the PR with a summary of your findings." >> /tmp/cursor_review_prompt.txt
          echo "" >> /tmp/cursor_review_prompt.txt
          echo "---" >> /tmp/cursor_review_prompt.txt
          echo "" >> /tmp/cursor_review_prompt.txt
          echo "$INSTRUCTIONS" >> /tmp/cursor_review_prompt.txt

      - name: Run Cursor Review
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run cursor-agent with the review instructions and permission to post comments
          cursor-agent -p "$(cat /tmp/cursor_review_prompt.txt)" --model gpt-5 --force

  unauthorized-message:
    # Post message for unauthorized users
    if: |
      (
        github.event_name == 'issue_comment' ||
        github.event_name == 'pull_request_review_comment'
      ) &&
      contains(github.event.comment.body, '@cursor-review') &&
      !contains(fromJSON('["ryanjosebrosas"]'), github.event.comment.user.login)

    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Post unauthorized message
        uses: actions/github-script@v7
        with:
          script: |
            const comment = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ @${context.actor} - You are not authorized to trigger Cursor reviews.\n\nOnly the maintainers can trigger Cursor: Please ask a maintainer for review.`
            };

            if (context.eventName === 'issue_comment') {
              await github.rest.issues.createComment({
                ...comment,
                issue_number: context.issue.number
              });
            } else if (context.eventName === 'pull_request_review_comment') {
              await github.rest.pulls.createReplyForReviewComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                comment_id: context.payload.comment.id,
                body: comment.body
              });
            }
